### ISSUE TITLE
Wrong implementation in load_first_output_index while type script is missing

### ISSUE THREAD

**Issue by XuJiandong** [quake/global-registry#1]
```Rust
fn load_first_output_index() -> Result<usize, Error> {
    let current_script_hash = load_script_hash()?;

    let mut i = 0;
    while let Some(type_hash) = load_cell_type_hash(i, Source::Output)? {
        if type_hash == current_script_hash {
            return Ok(i);
        }
        i += 1
    }
    unreachable!()
}
```
When type script is missing, it returns `None` which breaks the loop.

**Comment by quake** [comment]
the type script won't be missed in outputs since we invoke it after fn `is_init`, when `is_init` returns true, at least one output with current type script must be presented, so I use `unreachable` in the last line code.

**Comment by XuJiandong** [comment]
It might be true for GroupOutput, But not for `Output`. A type script can be missing for some other cell in same transaction.

**Comment by quake** [comment]
~~yes, it's a typo, should be GroupInput~~

**Comment by quake** [comment]
resolved by https://github.com/quake/global-registry/commit/a149f72b7d1e6ce34bec75117cc173b67e8cfb58

please help to review again, thanks.
